import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#88a9d6' },
  header: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: 'white', 
    marginTop: 50, 
    marginHorizontal: 15, 
    padding: 15, 
    borderRadius: 15,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#1d50a2', marginLeft: 15 },
  scrollContent: { padding: 15, paddingBottom: 40 },
  menuCard: { 
    backgroundColor: 'white', 
    borderRadius: 25, 
    padding: 20, 
    minHeight: 450,
    elevation: 5,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  menuTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 15, marginTop: 10, color: '#777', textTransform: 'uppercase' },
  optionRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: '#fff', 
    padding: 16, 
    borderRadius: 15, 
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  iconContainer: { width: 35, alignItems: 'center' },
  optionLabel: { fontSize: 16, fontWeight: '600', marginLeft: 10, flex: 1 },
  chevron: { marginLeft: 'auto' },
  divider: { height: 1, backgroundColor: '#eee', marginVertical: 15 },
  versionText: { textAlign: 'center', marginTop: 20, color: '#eef2ff', fontSize: 12, fontWeight: '500' },
  // 🛑 Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    width: '85%',
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 5 },
  },
  modalIconContainer: {
    backgroundColor: '#fdeeea',
    padding: 15,
    borderRadius: 50,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333',
    marginBottom: 8,
  },
  modalSub: {
    fontSize: 15,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    marginRight: 10,
    alignItems: 'center',
  },
  modalCancelText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 16,
  },
  modalConfirmBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#d9534f',
    marginLeft: 10,
    alignItems: 'center',
  },
  modalConfirmText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },

  
});